# shellcheck shell=sh
#
# codeg SSH remote-workspace bootstrap.
#
# Fed to the remote host on stdin (`ssh <host> sh -s`), never written to the
# remote filesystem and never fetched from the network. Every value it needs is
# injected as a prelude of assignments generated by `ssh::bootstrap` on the
# desktop side, so nothing in here is interpolated from user input and there is
# no remote shell quoting to get wrong.
#
# Contract: exactly one line on stdout of the form
#
#     CODEG_BOOTSTRAP_RESULT {"status":"ok",...}
#     CODEG_BOOTSTRAP_RESULT {"status":"error","code":"...","message":"..."}
#
# Anything else on stdout (login banners, shell rc chatter) is ignored by the
# parser, which scans for the sentinel. Diagnostics go to stderr, and MUST never
# contain the token — the desktop side redacts as a second layer, but the first
# layer is not printing it.
#
# Runs as the logged-in user. No sudo, no systemd, no PATH mutation, nothing
# written outside $CODEG_REMOTE_ROOT.
#
# ## stdin discipline
#
# This script *is* the shell's stdin. Any child that reads stdin would swallow
# the not-yet-parsed remainder of the script, so every child that might read it
# gets an explicit `</dev/null`. That is also why the bearer token is passed to
# curl through a 0600 config file rather than `curl --config -`: the stdin slot
# is already taken.

set -u

# Every file this script creates holds either a bearer token or the server's
# stderr (which contains the token on first run). 077 from the first line, so
# there is no window where a fresh file is group/world readable.
umask 077

SENTINEL="CODEG_BOOTSTRAP_RESULT"

# ── Reply helpers ──────────────────────────────────────────────────────────
#
# JSON is assembled by hand from values this script controls: integers, a hex
# token, a version string matched against a strict pattern, and fixed message
# literals. No user-supplied text reaches these, so no escaping is required.

emit_error() {
  printf '%s {"status":"error","code":"%s","message":"%s"}\n' \
    "$SENTINEL" "$1" "$2"
  exit 0
}

log() {
  # stderr only. The caller treats stderr as diagnostics and redacts it before
  # it can reach a log file or an error message.
  printf '[codeg-bootstrap] %s\n' "$1" >&2
}

# ── Injected configuration ────────────────────────────────────────────────

: "${CODEG_REMOTE_VERSION:?missing CODEG_REMOTE_VERSION}"
: "${CODEG_REMOTE_ROOT_NAME:?missing CODEG_REMOTE_ROOT_NAME}"
: "${CODEG_REMOTE_RELEASE_BASE:?missing CODEG_REMOTE_RELEASE_BASE}"
: "${CODEG_REMOTE_PORT_MIN:?missing CODEG_REMOTE_PORT_MIN}"
: "${CODEG_REMOTE_PORT_MAX:?missing CODEG_REMOTE_PORT_MAX}"
: "${CODEG_REMOTE_START_ATTEMPTS:?missing CODEG_REMOTE_START_ATTEMPTS}"
: "${CODEG_REMOTE_READY_TIMEOUT:?missing CODEG_REMOTE_READY_TIMEOUT}"
: "${CODEG_REMOTE_LOCK_WAIT:?missing CODEG_REMOTE_LOCK_WAIT}"

# ── Preconditions ─────────────────────────────────────────────────────────

[ "$(uname -s 2>/dev/null || echo unknown)" = "Linux" ] ||
  emit_error unsupported_os "Only Linux remote hosts are supported."

case "$(uname -m 2>/dev/null || echo unknown)" in
x86_64 | amd64) ARCH_SUFFIX=x64 ;;
aarch64 | arm64) ARCH_SUFFIX=arm64 ;;
*) emit_error unsupported_arch \
  "Only x86_64 and aarch64 Linux hosts are supported." ;;
esac

# The upstream release binaries are built against glibc on Ubuntu 22.04. On a
# musl host (Alpine) they would either fail to exec or die on a missing
# interpreter far from here, so refuse up front with something actionable.
if (ldd --version 2>&1 </dev/null || true) | head -n 1 | grep -qi musl; then
  emit_error unsupported_libc \
    "This host uses musl libc; the prebuilt Linux binaries require glibc."
fi

# `flock` is a hard requirement, not a nicety. It is the only lock primitive
# here that cannot be corrupted by a holder dying at the wrong moment: the
# kernel releases an flock when the fd closes, however the process ended. A
# mkdir/pidfile lock has an unavoidable window between "directory created" and
# "pid recorded" in which a second bootstrap sees an ownerless lock, and any
# recovery rule for that window either deletes a live lock (two servers, one
# database) or wedges the host forever. Refusing to run without flock is the
# honest trade — it ships in util-linux on every glibc distro.
for tool in curl tar flock; do
  command -v "$tool" >/dev/null 2>&1 </dev/null ||
    emit_error "missing_${tool}" "Required command '${tool}' was not found on the remote host."
done

# One of these is needed to verify the release checksum. Refusing to install
# without a verifier is deliberate: an unverified tarball is the one thing worth
# failing the whole flow over.
if command -v sha256sum >/dev/null 2>&1 </dev/null; then
  SHA_CMD="sha256sum"
elif command -v shasum >/dev/null 2>&1 </dev/null; then
  SHA_CMD="shasum -a 256"
else
  emit_error missing_sha256 \
    "Neither sha256sum nor shasum is available, so the download cannot be verified."
fi

HOME_DIR="${HOME:-}"
[ -n "$HOME_DIR" ] && [ -d "$HOME_DIR" ] ||
  emit_error no_home "The remote account has no usable HOME directory."

# ── Layout ────────────────────────────────────────────────────────────────
#
# A single fixed root under the user's home. `data/` deliberately does NOT
# coincide with the default a manually installed codeg-server would pick
# (~/.codeg), so an SSH workspace never opens, migrates or shares the database
# of an existing deployment on the same host.

ROOT="${HOME_DIR}/${CODEG_REMOTE_ROOT_NAME}"
VERSIONS_DIR="${ROOT}/versions"
INSTALL_DIR="${VERSIONS_DIR}/${CODEG_REMOTE_VERSION}"
DATA_DIR="${ROOT}/data"
RUN_DIR="${ROOT}/run"
LOG_DIR="${ROOT}/logs"
STATE_FILE="${RUN_DIR}/instance.env"
LOCK_FILE="${RUN_DIR}/bootstrap.lock"
SERVER_LOG="${LOG_DIR}/server.log"

for dir in "$ROOT" "$VERSIONS_DIR" "$INSTALL_DIR" "$DATA_DIR" "$RUN_DIR" "$LOG_DIR"; do
  [ ! -L "$dir" ] || emit_error unsafe_path "The codeg install directories must not be symlinks."
done
mkdir -p "$VERSIONS_DIR" "$DATA_DIR" "$RUN_DIR" "$LOG_DIR" 2>/dev/null ||
  emit_error mkdir_failed "Could not create the codeg directory under the remote home."
chmod 700 "$ROOT" "$RUN_DIR" "$LOG_DIR" "$DATA_DIR" 2>/dev/null ||
  emit_error permissions_failed "Could not protect the codeg directories."

# Scratch paths this run owns, cleaned unconditionally on the way out.
CURL_AUTH_CFG="${RUN_DIR}/curl-auth.$$.cfg"
HEALTH_BODY="${RUN_DIR}/health.$$.json"
TMP_DIR="${ROOT}/tmp.$$"

cleanup() {
  rm -f "$CURL_AUTH_CFG" "$HEALTH_BODY" 2>/dev/null || true
  rm -rf "$TMP_DIR" 2>/dev/null || true
}

# The lock lives on fd 9 and is released by the kernel when this shell exits, so
# cleanup never has to (and never should) delete the lock *file* — deleting it
# would let the next run lock a fresh inode while this one still holds the old.
trap 'cleanup' EXIT
# An interrupted run must not carry on unlocked: the signal traps exit, they do
# not merely tidy up. `exit` here also fires the EXIT trap and drops fd 9.
trap 'log "interrupted"; exit 1' INT TERM HUP

# ── Lock ──────────────────────────────────────────────────────────────────
#
# One bootstrap per host at a time. Without this, two desktop windows opening
# the same workspace at once would both install and both start a server, leaving
# two processes on two ports against one SQLite database.

exec 9>>"$LOCK_FILE" ||
  emit_error lock_failed "Could not open the bootstrap lock file."
chmod 600 "$LOCK_FILE" 2>/dev/null || true

if ! flock -w "$CODEG_REMOTE_LOCK_WAIT" 9; then
  emit_error lock_timeout \
    "Another codeg bootstrap is still running on this host; it did not finish in time."
fi

# ── Existing instance ─────────────────────────────────────────────────────

RUNNING_PORT=""
RUNNING_TOKEN=""
RUNNING_PID=""
RUNNING_VERSION=""

if [ -f "$STATE_FILE" ]; then
  # The state file is written by this script only, as four `KEY=value` lines
  # with values from a constrained alphabet. Read it field by field rather than
  # sourcing it, so a corrupted file cannot execute anything.
  RUNNING_PORT="$(sed -n 's/^PORT=\([0-9][0-9]*\)$/\1/p' "$STATE_FILE" | tail -n 1)"
  RUNNING_PID="$(sed -n 's/^PID=\([0-9][0-9]*\)$/\1/p' "$STATE_FILE" | tail -n 1)"
  RUNNING_TOKEN="$(sed -n 's/^TOKEN=\([0-9a-f][0-9a-f]*\)$/\1/p' "$STATE_FILE" | tail -n 1)"
  RUNNING_VERSION="$(sed -n 's/^VERSION=\([0-9A-Za-z._-][0-9A-Za-z._-]*\)$/\1/p' "$STATE_FILE" | tail -n 1)"
fi

# Is `$1` a live process running a codeg-server out of *our* install root?
#
# A recorded pid proves nothing on its own: pid numbers are recycled, and after a
# reboot the number in a stale state file is overwhelmingly likely to belong to
# some unrelated process of this user. `/proc/<pid>/exe` is the identity check —
# it resolves to the actual executable backing the process, so a recycled pid
# fails it. Everything that acts on a recorded pid goes through here first.
pid_is_our_server() {
  _pid="$1"
  case "$_pid" in
  '' | *[!0-9]*) return 1 ;;
  esac
  kill -0 "$_pid" 2>/dev/null || return 1
  _exe="$(readlink "/proc/${_pid}/exe" 2>/dev/null || echo '')"
  # A replaced binary reads back as "<path> (deleted)"; that is still our
  # process, so compare on the path with the suffix removed.
  _exe="${_exe% (deleted)}"
  case "$_exe" in
  "${VERSIONS_DIR}/"*"/codeg-server") return 0 ;;
  *) return 1 ;;
  esac
}

# Authenticated health probe. Sets HEALTH_VERSION on success.
#
# The bearer token goes in a 0600 config file, never in argv: `/proc/*/cmdline`
# is world-readable on a default Linux, so an argv header would publish the
# credential to every other account on the remote host for the lifetime of the
# call. Config-file input also can't come from stdin here — the shell is still
# reading this script from it.
HEALTH_VERSION=""
health_ok() {
  _port="$1"
  _token="$2"
  HEALTH_VERSION=""
  [ -n "$_port" ] && [ -n "$_token" ] || return 1

  # Truncate-and-rewrite under the script-wide umask 077. The token is validated
  # hex elsewhere, so it needs no escaping inside curl's quoted config value.
  : >"$CURL_AUTH_CFG" || return 1
  chmod 600 "$CURL_AUTH_CFG" 2>/dev/null || true
  printf 'header = "Authorization: Bearer %s"\n' "$_token" >"$CURL_AUTH_CFG" || return 1

  rm -f "$HEALTH_BODY" 2>/dev/null || true
  curl -q --noproxy '*' -fsS --max-time 5 -K "$CURL_AUTH_CFG" \
    -o "$HEALTH_BODY" \
    -X POST \
    -H 'Content-Type: application/json' \
    -d '{}' \
    "http://127.0.0.1:${_port}/api/health" </dev/null 2>/dev/null || return 1

  # A 2xx is not enough: any local service could answer 200 on a recycled port.
  # Require the body codeg-server's own `/api/health` produces, and take the
  # version from *that* — the state file only records what we asked for, which is
  # not evidence of what is actually serving.
  _body="$(tr -d ' \n\r\t' <"$HEALTH_BODY" 2>/dev/null || echo '')"
  case "$_body" in
  *'"status":"ok"'*) ;;
  *) return 1 ;;
  esac
  HEALTH_VERSION="$(printf '%s' "$_body" |
    sed -n 's/.*"version":"\([0-9A-Za-z._-]*\)".*/\1/p' | head -n 1)"
  return 0
}

if pid_is_our_server "$RUNNING_PID" && health_ok "$RUNNING_PORT" "$RUNNING_TOKEN"; then
  # Reuse wins over upgrading, always. A second server started on a newer
  # version would open the same database and could run migrations under the feet
  # of the live one. The desktop is told which version it actually got, taken
  # from the live health response rather than from the state file.
  log "reusing running instance on port ${RUNNING_PORT}"
  printf '%s {"status":"ok","port":%s,"token":"%s","version":"%s","reused":true,"requestedVersion":"%s"}\n' \
    "$SENTINEL" "$RUNNING_PORT" "$RUNNING_TOKEN" \
    "${HEALTH_VERSION:-${RUNNING_VERSION:-unknown}}" "$CODEG_REMOTE_VERSION"
  exit 0
fi

# Not reusable. There is deliberately no kill path here.
#
# Two distinct situations reach this point and neither justifies a signal:
#
#   - The pid is alive but is NOT our server (recycled number, or a state file
#     that outlived a reboot). Signalling it would kill an unrelated process of
#     the user's — the state file is not evidence of ownership, so we treat it as
#     stale and simply stop believing it.
#   - The pid IS our server but health failed. That server may well be mid-prompt
#     on somebody's agent run; a transient health failure (load, a long GC pause,
#     a wedged request) is not grounds for killing the work. Starting a second
#     server against the same database would be worse still, so we stop and say
#     so, and let the user decide.
if pid_is_our_server "$RUNNING_PID"; then
  log "instance pid ${RUNNING_PID} is alive but not answering the health check"
  emit_error instance_unhealthy \
    "A codeg-server from a previous session is still running on this host but is not responding. It was left alone in case agents are still working; stop it yourself on the remote host, then reconnect."
fi

if [ -n "$RUNNING_PID" ]; then
  log "recorded pid ${RUNNING_PID} is not our server; treating the state file as stale"
fi
rm -f "$STATE_FILE" 2>/dev/null || true

# ── Install ───────────────────────────────────────────────────────────────

SERVER_BIN="${INSTALL_DIR}/codeg-server"
MCP_BIN="${INSTALL_DIR}/codeg-mcp"
WEB_DIR="${INSTALL_DIR}/web"

install_release() {
  artifact="codeg-server-linux-${ARCH_SUFFIX}"
  url="${CODEG_REMOTE_RELEASE_BASE}/v${CODEG_REMOTE_VERSION}/${artifact}.tar.gz"
  rm -rf "$TMP_DIR"
  mkdir -p "$TMP_DIR" || return 1

  log "downloading ${url}"
  curl -q --proto '=https' --proto-redir '=https' -fsSL --max-time 300 -o "${TMP_DIR}/bundle.tar.gz" "$url" </dev/null ||
    emit_error download_failed \
      "Could not download the codeg-server release for this version and architecture."
  curl -q --proto '=https' --proto-redir '=https' -fsSL --max-time 120 -o "${TMP_DIR}/bundle.sha256" "${url}.sha256" </dev/null ||
    emit_error checksum_unavailable \
      "The release checksum could not be downloaded, so the archive was not trusted."

  # The published file is `<hash>  <artifact>.tar.gz`; compare hashes directly
  # rather than relying on `-c`, whose filename column would not match our
  # temporary name.
  expected="$(awk 'NR==1{print $1}' "${TMP_DIR}/bundle.sha256" | tr 'A-F' 'a-f')"
  [ "${#expected}" -eq 64 ] ||
    emit_error checksum_malformed "The published checksum is not a SHA-256 hash."
  actual="$($SHA_CMD "${TMP_DIR}/bundle.tar.gz" </dev/null | awk '{print $1}')"
  case "$expected" in
  '' | *[!0-9a-fA-F]*)
    emit_error checksum_malformed "The published checksum for this release is not a valid hash."
    ;;
  esac
  if [ "$expected" != "$actual" ]; then
    emit_error checksum_mismatch \
      "The downloaded archive did not match the published checksum and was discarded."
  fi
  log "checksum verified"

  tar xzf "${TMP_DIR}/bundle.tar.gz" -C "$TMP_DIR" </dev/null ||
    emit_error extract_failed "The release archive could not be extracted."

  # `codeg-mcp` is not optional: it is the companion the server spawns per
  # delegation session. An install missing it would degrade silently at the
  # first sub-agent call, so treat it as a broken archive.
  for name in codeg-server codeg-mcp; do
    [ -f "${TMP_DIR}/${artifact}/${name}" ] ||
      emit_error incomplete_archive \
        "The release archive is missing a required binary and was discarded."
  done

  # Stage into a scratch directory and move into place, so a failure never
  # leaves a half-populated version directory that later runs would trust.
  staged="${TMP_DIR}/staged"
  mkdir -p "$staged" || return 1
  cp "${TMP_DIR}/${artifact}/codeg-server" "${staged}/codeg-server" || return 1
  cp "${TMP_DIR}/${artifact}/codeg-mcp" "${staged}/codeg-mcp" || return 1
  chmod 700 "${staged}/codeg-server" "${staged}/codeg-mcp" || return 1
  if [ -d "${TMP_DIR}/${artifact}/web" ]; then
    cp -R "${TMP_DIR}/${artifact}/web" "${staged}/web" || return 1
  fi

  rm -rf "$INSTALL_DIR"
  mkdir -p "$VERSIONS_DIR" || return 1
  mv "$staged" "$INSTALL_DIR" ||
    emit_error install_failed "The verified release could not be moved into place."
  rm -rf "$TMP_DIR"
  log "installed version ${CODEG_REMOTE_VERSION}"
}

INSTALLED_FRESH=false
if [ -x "$SERVER_BIN" ] && [ -x "$MCP_BIN" ]; then
  log "version ${CODEG_REMOTE_VERSION} already installed"
else
  install_release || emit_error install_failed "The codeg-server install did not complete."
  INSTALLED_FRESH=true
fi

# ── Token ─────────────────────────────────────────────────────────────────
#
# Minted on the remote host and pinned via CODEG_TOKEN, for two reasons. It
# never crosses a network in the clear (it is read back through this SSH
# channel), and pinning it means the server never prints the
# "generated an access token" line that would otherwise put the credential in
# its stderr log.

TOKEN_FILE="${RUN_DIR}/token"
if [ -s "$TOKEN_FILE" ]; then
  TOKEN="$(tr -dc 'a-f0-9' <"$TOKEN_FILE" | head -c 64)"
else
  TOKEN=""
fi
if [ "${#TOKEN}" -ne 64 ]; then
  if [ -r /dev/urandom ]; then
    TOKEN="$(tr -dc 'a-f0-9' </dev/urandom 2>/dev/null | head -c 64)"
  else
    TOKEN=""
  fi
  [ "${#TOKEN}" -eq 64 ] ||
    emit_error token_failed "Could not generate an access token on the remote host."
  (
    umask 077
    printf '%s' "$TOKEN" >"$TOKEN_FILE"
  ) || emit_error token_failed "Could not store the access token on the remote host."
fi
chmod 600 "$TOKEN_FILE" 2>/dev/null ||
  emit_error permissions_failed "Could not protect the server token file."

# ── Start ─────────────────────────────────────────────────────────────────
#
# Port selection by attempt rather than by probing: `ss`/`netstat`/`lsof` are
# not all guaranteed to exist, and a probe is a race anyway. Pick a port, try to
# come up on it, and move on to another if the server does not answer.

random_port() {
  span=$((CODEG_REMOTE_PORT_MAX - CODEG_REMOTE_PORT_MIN + 1))
  if [ -r /dev/urandom ]; then
    n="$(od -An -N2 -tu2 </dev/urandom 2>/dev/null | tr -d ' \n')"
  else
    n=""
  fi
  case "$n" in
  '' | *[!0-9]*) n="$$" ;;
  esac
  printf '%s\n' "$((CODEG_REMOTE_PORT_MIN + n % span))"
}

record_state() {
  (
    umask 077
    {
      printf 'PORT=%s\n' "$1"
      printf 'PID=%s\n' "$2"
      printf 'TOKEN=%s\n' "$TOKEN"
      printf 'VERSION=%s\n' "$3"
    } >"${STATE_FILE}.tmp"
  ) && chmod 600 "${STATE_FILE}.tmp" && mv -f "${STATE_FILE}.tmp" "$STATE_FILE"
}

attempt=0
STARTED_PORT=""
STARTED_PID=""
STARTED_VERSION=""
while [ "$attempt" -lt "$CODEG_REMOTE_START_ATTEMPTS" ]; do
  attempt=$((attempt + 1))
  port="$(random_port)"
  log "starting codeg-server on 127.0.0.1:${port} (attempt ${attempt})"

  # The log file holds the server's stderr. It is created 600 before the server
  # can write a line to it.
  : >>"$SERVER_LOG" 2>/dev/null || true
  chmod 600 "$SERVER_LOG" 2>/dev/null || true

  # Detached on purpose. `nohup` + `&` + redirected stdio means the process
  # survives this SSH session closing, which is the whole point: the user's
  # agents keep running when the desktop app quits or the network drops, and
  # the next connect reuses this instance instead of restarting work.
  #
  # `CODEG_HOST=127.0.0.1` keeps it off the remote host's network entirely — the
  # only way in is the SSH forward.
  #
  # `</dev/null` so it can never read (and consume) this script from the shared
  # stdin, and so it sees a clean EOF rather than a closed pipe.
  #
  # `9>&-` closes the inherited bootstrap lock fd in the child. Without it the
  # long-lived server would hold the flock for its entire life, and every later
  # bootstrap — including the one that just wants to reuse this very instance —
  # would time out on the lock.
  CODEG_HOST=127.0.0.1 \
    CODEG_PORT="$port" \
    CODEG_TOKEN="$TOKEN" \
    CODEG_DATA_DIR="$DATA_DIR" \
    CODEG_HOME="$DATA_DIR" \
    CODEG_STATIC_DIR="$WEB_DIR" \
    nohup "$SERVER_BIN" </dev/null >>"$SERVER_LOG" 2>&1 9>&- &
  pid=$!
  # Record ownership before waiting. If SSH disconnects mid-start, the next
  # bootstrap can adopt this child instead of starting a second database owner.
  record_state "$port" "$pid" "$CODEG_REMOTE_VERSION" ||
    emit_error state_failed "Could not record the remote instance state."

  waited=0
  while [ "$waited" -lt "$CODEG_REMOTE_READY_TIMEOUT" ]; do
    if ! kill -0 "$pid" 2>/dev/null; then
      log "server exited during startup"
      break
    fi
    if health_ok "$port" "$TOKEN"; then
      STARTED_PORT="$port"
      STARTED_PID="$pid"
      STARTED_VERSION="$HEALTH_VERSION"
      break
    fi
    waited=$((waited + 1))
    sleep 1
  done

  if [ -n "$STARTED_PORT" ]; then
    break
  fi
  # Killing *this* pid is sound where killing a recorded one is not: we forked it
  # seconds ago in this very loop and it never became ready, so there is no
  # ambiguity about identity and no agent work to lose.
  if pid_is_our_server "$pid"; then
    kill "$pid" 2>/dev/null || true
  fi
  wait "$pid" 2>/dev/null || true
  rm -f "$STATE_FILE"
done

if [ -z "$STARTED_PORT" ]; then
  # The server's own stderr is the only useful diagnostic here, and it is
  # exactly the stream that can contain a token, so it is not echoed. The
  # desktop points the user at this path instead.
  emit_error start_failed \
    "codeg-server did not become ready on the remote host. See the server log under the codeg directory."
fi

record_state "$STARTED_PORT" "$STARTED_PID" "${STARTED_VERSION:-$CODEG_REMOTE_VERSION}" ||
  emit_error state_failed "Could not record the remote instance state."

printf '%s {"status":"ok","port":%s,"token":"%s","version":"%s","reused":false,"installed":%s}\n' \
  "$SENTINEL" "$STARTED_PORT" "$TOKEN" \
  "${STARTED_VERSION:-$CODEG_REMOTE_VERSION}" "$INSTALLED_FRESH"
